name = "arcade-monitor"
main = "build/worker/shim.mjs"
compatibility_date = "2024-06-29"

[build]
command = "cargo install worker-build && worker-build --release"

[triggers]
crons = ["*/20 * * * *"] # Run every twenty minutes

[placement]
mode = "smart"

[vars]
NTFY_URL = "https://ntfy.hackclub.app/arcade-monitor"
ARCADE_SHOP_URL = "https://hackclub.com/arcade/shop/"
SLACK_GROUP_ID = "S07B2CBT2DV"

[[kv_namespaces]]
binding = "SHOP_ITEMS"
id = "076e9724967c49619e34d180ebfb5e6a"
